name: Build Windows Release & Installer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'
        cache: true

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Enable Windows Desktop
      run: flutter config --enable-windows-desktop

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Windows Release
      run: flutter build windows --release

    - name: Compile Inno Setup Installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\iscc.exe" setup.iss
      shell: pwsh

    - name: Upload Windows Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ResultMax-Setup-Installer
        path: output/ResultMax_Setup.exe
    - name: Upload Unzipped Release Folder (Backup)
      uses: actions/upload-artifact@v4
      with:
        name: ResultMax-Windows-Release
        path: build/windows/x64/runner/Release/
